#pragma once

enum class RENDERCTRLTYPE
{
	RENDER_NONE = -1,
	RENDER_TEXT = 0,
	RENDER_SHADOW = 1,
	RENDER_IMAGE = 2,
	RENDER_IMAGE_TILE = 3,
	RENDER_IMAGE_STRETCH = 4,
	RENDER_3DOBJ = 5,
	RENDER_TEXT_FOCUS = 6,
};

enum class TMEITEMTYPE
{
	ITEMTYPE_NONE = 0,
	ITEMTYPE_HELM = 2,
	ITEMTYPE_COAT = 4,
	ITEMTYPE_PANTS = 8,
	ITEMTYPE_GLOVES = 16,
	ITEMTYPE_BOOTS = 32,
	ITEMTYPE_LEFT = 64,
	ITEMTYPE_RIGHT = 128,
	ITEMTYPE_RING = 256,
	ITEMTYPE_NECKLACE = 512,
	ITEMTYPE_ORB = 1024,
	ITEMTYPE_CABUNCLE = 2048,
	ITEMTYPE_GUILD = 4096,
	ITEMTYPE_EVENT = 8192,
	ITEMTYPE_MOUNT = 16384,
	ITEMTYPE_MANTUA = 32768,
	ITEMTYPE_NEWSLOT1 = 65536,
	ITEMTYPE_NEWSLOT2 = 131072,
};

enum class ECHAR_MOTION
{
	ECMOTION_NONE = -1,
	ECMOTION_STAND01 = 0,
	ECMOTION_STAND02 = 1,
	ECMOTION_WALK = 2,
	ECMOTION_RUN = 3,
	ECMOTION_ATTACK01 = 4,
	ECMOTION_ATTACK02 = 5,
	ECMOTION_ATTACK03 = 6,
	ECMOTION_ATTACK04 = 7,
	ECMOTION_ATTACK05 = 8,
	ECMOTION_ATTACK06 = 9,
	ECMOTION_STRIKE = 10,
	ECMOTION_DIE = 11,
	ECMOTION_DEAD = 12,
	ECMOTION_SEAT = 13,
	ECMOTION_LEVELUP = 14,
	ECMOTION_PUNISH = 15,
	ECMOTION_CACKLE = 16,
	ECMOTION_YAWN = 17,
	ECMOTION_MERCHANT_LOUNGE = 18,
	ECMOTION_RELAX = 19,
	ECMOTION_NEVER = 20,
	ECMOTION_COMEON = 21,
	ECMOTION_SALUTE = 22,
	ECMOTION_HOLYTOUCH = 23,
	ECMOTION_SEATING = 24,
	ECMOTION_STAND03 = 25,
	ECMOTION_PUNISHING = 26,
	ECMOTION_PUNEND = 27,
};
