
void MainThread(void * lpParam);
void Dll_Inject();
void DLL_Inject_Thread();
void AddItems();
void Carrega_Minimizer();
void LA_On_byName();
void Heuristica2();
void SPerformance();
void DetectSpeed();
void AntiKill();
void DetectID();
void ClienteThread();
void ServerThread();
void GameGuard_Protection();
void Startup_Protection();
void CheckConfigFile(); 
void CheckConfigFileL();
void Mac_Load();
void SplashShow();
void Hack_Log_Up();
void Close_Class();
void Close_Window();
void ExeByFileSize();
void Anti_kill1();
void Anti_kill2();
void Nomes();
void DwProtection();
void TxtCheckWindow();
void HProtection();
void HeuristicW();
void Heuristicclass();
void CNProtection();
void Serial_e_Etc();
void HTTP_Connect();
void Hide_T();
void Virtual_Attack();							  
void RebuildData();
void Dll_API_Count();
void TESTES();
void tokenPrivilege();
void Exists_Registry();
void Exists_Startup();
void LoadSingleInstance();
int DenyAdm();
int Dll_Protection();
int ProtectionDump();
int DisableASLR();

//Antikill

void PHP_New_Tread(); //From antikill / ban server integration
void DAka();
void DAkb();
void CloseClas();
void CloseWin();
void DClass();
void DDump();
void DHeuri();
void DHeuriNC();
void DHeuriWin(); 
void DHeuriClass();
void DHide();
void DInject();
void Dname();
void DProcID();
void DSpeed();
void DWin();
void DHard();
void DLauncher();
void DBan();
void DVirtualM();
void DSPerf();
void DVirtualExe();
void DTxtFileSize();
void Dpipe();
void Kill_From_Message_Warning();
						 
